"""empty message

Revision ID: 612db1c14377
Revises: f576dc026d9d
Create Date: 2024-01-14 02:17:41.538956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '612db1c14377'
down_revision = 'f576dc026d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('rfid', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('warehouse', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Shelves', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
