"""empty message

Revision ID: df7bd14d4698
Revises: 3871e0a4c933
Create Date: 2024-01-12 23:32:32.319051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7bd14d4698'
down_revision = '3871e0a4c933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound', sa.Column('lm', sa.String(length=200), nullable=True))
    op.add_column('inbound', sa.Column('diameter', sa.String(length=200), nullable=True))
    op.add_column('inbound', sa.Column('kg', sa.String(length=200), nullable=True))
    op.add_column('outbound', sa.Column('lm', sa.String(length=200), nullable=True))
    op.add_column('outbound', sa.Column('diameter', sa.String(length=200), nullable=True))
    op.add_column('outbound', sa.Column('kg', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbound', 'kg')
    op.drop_column('outbound', 'diameter')
    op.drop_column('outbound', 'lm')
    op.drop_column('inbound', 'kg')
    op.drop_column('inbound', 'diameter')
    op.drop_column('inbound', 'lm')
    # ### end Alembic commands ###
