"""empty message

Revision ID: f576dc026d9d
Revises: df7bd14d4698
Create Date: 2024-01-14 02:17:00.137743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f576dc026d9d'
down_revision = 'df7bd14d4698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbound', sa.Column('warehouse', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbound', 'warehouse')
    # ### end Alembic commands ###
